### ISSUE TITLE
Add ASM Support 

### ISSUE THREAD

**Issue by eliuha** [F5Networks/f5-common-python#546]

**Comment by caphrim007** [comment]
@eliuha Which ASM endpoints/features are of particular interest and on which version of BIG-IP? Assuming we want to prioritize the most important endpoints and not just blindly start writing

**Comment by eliuha** [comment]
The features I mostly use are creating an provisioning policies.
- create
- export
- backup 
- move to another machine (this one more of a use case, but let's keep it in mind)

In addition, I would love the ASU deploy options, like update from ESDM and from the file I have on my disk.

**Comment by wojtek0806** [comment]
@eliuha can you be more specific please? 

> In addition, I would love the ASU deploy options, like update from ESDM and from the file I have on my disk.

**Comment by eliuha** [comment]
specifically, I would wrap the update_sigfile and implement its options 

root@segev-Active:/shared/images > vi /usr/share/ts/bin/update_sigfile.pl
GetOptions(
           'a|automatic!' => \$params{automatic_mode},
           'f|file=s' => \$params{filename},
           'u|user!' => \$params{flg_is_user_defined},
           'force!' => \$params{force},
           'username=s' => \$params{user_name},
           'check-interval!' => \$params{check_interval},
           'silent!' => \$params{silent},
          );

**Comment by wojtek0806** [comment]
apologies for the delay, i have started working on this today so we should have something next week or sooner

**Comment by wojtek0806** [comment]
We will use this issue to track the progress of ASM implementation, the following issues are opened and will be implemented in first phase:
#700 - Add ASMFileUploadMixin 
#701 - Add ASM specific resource classes 
#702 - Add ASM sub-module in **init** and Asm tasks endpoint 
#703 - Add Asm File-Transfer endpoint 
#704 - Add Asm signature sets endpoint 
#705 - Add asm signature statuses endpoint 
#706 - Add asm signature systems endpoint 
#707 - Add asm signature update endpoint 
#708 - Add asm signatures endpoint

**Comment by wojtek0806** [comment]
- ASM Phase 1 - Completed in 100%:
- [x] #700 - Add ASMFileUploadMixin
- [x] #701 - Add ASM specific resource classes
- [x] #702 - Add ASM sub-module in init and Asm tasks endpoint
- [x] #703 - Add Asm File-Transfer endpoint
- [x] #704 - Add Asm signature sets endpoint
- [x] #705 - Add asm signature statuses endpoint
- [x] #706 - Add asm signature systems endpoint
- [x] #707 - Add asm signature update endpoint
- [x] #708 - Add asm signatures endpoint

**Comment by jasonrahm** [comment]
#828 - Add asm policies

Attn: @wojtek0806

**Comment by wojtek0806** [comment]
- ASM Phase 2 
- [x] #828 - Add Asm Policies - completed

Phase 2 Completed

**Comment by wojtek0806** [comment]
since most of endpoints are implemented closing this as completed
